return {
    currency = 'R$',
    mods = {
        {id = 0,  label = 'Spoiler',              category = 'parts'},
        {id = 1,  label = 'Para-choque dianteiro',         category = 'parts'},
        {id = 2,  label = 'Para-choque traseiro',          category = 'parts'},
        {id = 3,  label = 'Saia lateral',           category = 'parts'},
        {id = 4,  label = 'Escape',              category = 'parts'},
        {id = 5,  label = 'Gaiola de proteção',            category = 'parts'},
        {id = 6,  label = 'Grade',               category = 'parts'},
        {id = 7,  label = 'Capô',                 category = 'parts'},
        {id = 8,  label = 'Para-lama esquerdo',          category = 'parts'},
        {id = 9,  label = 'Para-lama direito',         category = 'parts'},
        {id = 10, label = 'Teto',                 category = 'parts'},
        {id = 11, label = 'Melhoria do motor',       category = 'performance'},
        {id = 12, label = 'Melhoria dos freios',        category = 'performance'},
        {id = 13, label = 'Melhoria da transmissão', category = 'performance'},
        {id = 14, label = 'Buzinas',                category = 'parts'},
        {id = 15, label = 'Melhoria da suspensão',   category = 'performance'},
        {id = 16, label = 'Melhoria da blindagem',        category = 'performance', enabled = false},
        {id = 17, label = 'Nitro',              category = 'performance', enabled = false},
        {id = 18, label = 'Melhoria do turbo',        category = 'performance'},
        {id = 19, label = 'Subwoofer',            category = 'parts'},
        -- {id = 20, label = 'Fumaça do pneu',                category = 'colors'},
        {id = 21, label = 'Hidráulica',           category = 'parts'},
        -- {id = 22, label = 'Faróis de xênon',         category = 'colors'},
        -- {id = 23, label = 'Rodas', category = 'parts'},
        -- {id = 24, label = 'Rodas traseiras ou hidráulica', category = 'parts'},
        {id = 25, label = 'Suporte de placa',         category = 'parts'},
        {id = 26, label = 'Saia frontal',        category = 'parts'},
        {id = 27, label = 'Guarnição A',               category = 'parts'},
        {id = 28, label = 'Ornamentos',            category = 'parts'},
        {id = 29, label = 'Painel',            category = 'parts'},
        {id = 30, label = 'Mostrador',                 category = 'parts'},
        {id = 31, label = 'Alto-falante de porta',         category = 'parts'},
        {id = 32, label = 'Assentos',                category = 'parts'},
        {id = 33, label = 'Volante',       category = 'parts'},
        {id = 34, label = 'Alavanca de câmbio',       category = 'parts'},
        {id = 35, label = 'Placa',               category = 'parts'},
        {id = 36, label = 'Alto-falante',              category = 'parts'},
        {id = 37, label = 'Porta-malas',                category = 'parts'},
        {id = 38, label = 'Hidráulico',            category = 'parts'},
        {id = 39, label = 'Bloco do motor',         category = 'parts'},
        {id = 40, label = 'Filtro de ar',           category = 'parts'},
        {id = 41, label = 'Estrutural',                category = 'parts'},
        {id = 42, label = 'Capa do arco',           category = 'parts'},
        {id = 43, label = 'Antena',               category = 'parts'},
        {id = 44, label = 'Guarnição B',               category = 'parts'},
        {id = 45, label = 'Tanque de combustível',            category = 'parts'},
        {id = 46, label = 'Entrada de ar lateral',            category = 'parts'},
        {id = 47, label = 'Farois',           category = 'parts'},
        -- {id = 48, label = 'Plotagem',               category = 'colors'},
        {id = 49, label = 'Barra de luz',             category = 'parts'},
    },    

    -- https://docs.fivem.net/natives/?_0x4F1D4BE3A7F24601
    paints = {
        Classic = {
            {id = 0,   label = 'Preto'},
            {id = 1,   label = 'Grafite'},
            {id = 2,   label = 'Aço Preto'},
            {id = 3,   label = 'Aço Escuro'},
            {id = 4,   label = 'Prata'},
            {id = 5,   label = 'Prata Azulada'},
            {id = 6,   label = 'Aço Laminado'},
            {id = 7,   label = 'Prata Sombra'},
            {id = 8,   label = 'Prata Pedra'},
            {id = 9,   label = 'Prata Meia-Noite'},
            {id = 10,  label = 'Ferro Fundido Prateado'},
            {id = 11,  label = 'Preto Antracite'},
            {id = 27,  label = 'Vermelho'},
            {id = 28,  label = 'Vermelho Torino'},
            {id = 29,  label = 'Vermelho Fórmula'},
            {id = 30,  label = 'Vermelho Chama'},
            {id = 31,  label = 'Vermelho Graça'},
            {id = 32,  label = 'Vermelho Granada'},
            {id = 33,  label = 'Vermelho Pôr do Sol'},
            {id = 34,  label = 'Vermelho Cabernet'},
            {id = 35,  label = 'Vermelho Doce'},
            {id = 36,  label = 'Laranja Nascente'},
            {id = 38,  label = 'Laranja'},
            {id = 49,  label = 'Verde Escuro'},
            {id = 50,  label = 'Verde de Corrida'},
            {id = 51,  label = 'Verde Mar'},
            {id = 52,  label = 'Verde Oliva'},
            {id = 53,  label = 'Verde Brilhante'},
            {id = 54,  label = 'Verde Gasolina'},
            {id = 61,  label = 'Azul Galáxia'},
            {id = 62,  label = 'Azul Escuro'},
            {id = 63,  label = 'Azul Saxão'},
            {id = 64,  label = 'Azul'},
            {id = 65,  label = 'Azul Marinho'},
            {id = 66,  label = 'Azul Porto'},
            {id = 67,  label = 'Azul Diamante'},
            {id = 68,  label = 'Azul Surf'},
            {id = 69,  label = 'Azul Náutico'},
            {id = 70,  label = 'Azul Ultra'},
            {id = 71,  label = 'Roxo Schafter'},
            {id = 72,  label = 'Roxo Spinnaker'},
            {id = 73,  label = 'Azul de Corrida'},
            {id = 74,  label = 'Azul Claro'},
            {id = 88,  label = 'Amarelo'},
            {id = 89,  label = 'Amarelo de Corrida'},
            {id = 90,  label = 'Bronze'},
            {id = 91,  label = 'Amarelo Orvalho'},
            {id = 92,  label = 'Verde Limão'},
            {id = 94,  label = 'Marrom Feltzer'},
            {id = 95,  label = 'Marrom Creeen'},
            {id = 96,  label = 'Marrom Chocolate'},
            {id = 97,  label = 'Marrom Maple'},
            {id = 98,  label = 'Marrom Sela'},
            {id = 99,  label = 'Marrom Clareado'},
            {id = 100, label = 'Marrom Musgo'},
            {id = 101, label = 'Marrom Bison'},
            {id = 102, label = 'Marrom Madeira'},
            {id = 103, label = 'Marrom Bege'},
            {id = 104, label = 'Marrom Sienna'},
            {id = 105, label = 'Marrom Areia'},
            {id = 106, label = 'Marrom Clareado'},
            {id = 107, label = 'Creme'},
            {id = 111, label = 'Branco Gelo'},
            {id = 112, label = 'Branco Geadal'},
            {id = 135, label = 'Rosa Choque'},
            {id = 136, label = 'Rosa Salmão'},
            {id = 137, label = 'Rosa Pfister'},
            {id = 138, label = 'Laranja Brilhante'},
            {id = 141, label = 'Azul Meia-Noite'},
            {id = 142, label = 'Roxo Meia-Noite'},
            {id = 143, label = 'Vermelho Vinho'},
            {id = 145, label = 'Roxo Brilhante'},
            {id = 147, label = 'Preto Carbono'},
            {id = 150, label = 'Vermelho Lava'},
        },    
        Matte = {
            {id = 12,  label = 'Preto'},
            {id = 13,  label = 'Cinza'},
            {id = 14,  label = 'Cinza Claro'},
            {id = 39,  label = 'Vermelho'},
            {id = 40,  label = 'Vermelho Escuro'},
            {id = 41,  label = 'Laranja'},
            {id = 42,  label = 'Amarelo'},
            {id = 55,  label = 'Verde Limão'},
            {id = 82,  label = 'Azul Escuro'},
            {id = 83,  label = 'Azul'},
            {id = 84,  label = 'Azul Meia-Noite'},
            {id = 131, label = 'Branco Gelo'},
            {id = 148, label = 'Roxo Schafter'},
            {id = 149, label = 'Roxo Meia-Noite'},
            {id = 151, label = 'Verde Floresta'},
            {id = 152, label = 'Oliva Escura'},
            {id = 153, label = 'Terra Escura'},
            {id = 154, label = 'Bege Deserto'},
            {id = 155, label = 'Verde Folhagem'},
        },
        Metal = {
            {id = 117, label = 'Aço Escovado'},
            {id = 118, label = 'Aço Preto Escovado'},
            {id = 119, label = 'Alumínio Escovado'},
            {id = 120, label = 'Cromo'},
            {id = 158, label = 'Ouro Puro'},
            {id = 159, label = 'Ouro Escovado'},
        },
        Worn = {
            {id = 21,  label = 'Preto'},
            {id = 22,  label = 'Grafite'},
            {id = 23,  label = 'Cinza Prateado'},
            {id = 24,  label = 'Prata'},
            {id = 25,  label = 'Prata Azulada'},
            {id = 26,  label = 'Prata Sombra'},
            {id = 46,  label = 'Vermelho'},
            {id = 47,  label = 'Vermelho Dourado'},
            {id = 48,  label = 'Vermelho Escuro'},
            {id = 58,  label = 'Verde Escuro'},
            {id = 59,  label = 'Verde'},
            {id = 60,  label = 'Lavagem Marinha'},
            {id = 85,  label = 'Azul Escuro'},
            {id = 86,  label = 'Azul'},
            {id = 87,  label = 'Azul Claro'},
            {id = 113, label = 'Bege Mel'},
            {id = 114, label = 'Marrom'},
            {id = 115, label = 'Marrom Escuro'},
            {id = 116, label = 'Bege Palha'},
            {id = 121, label = 'Branco Off'},
            {id = 123, label = 'Laranja'},
            {id = 124, label = 'Laranja Claro'},
            {id = 126, label = 'Amarelo Táxi'},
            {id = 130, label = 'Laranja'},
            {id = 132, label = 'Branco'},
            {id = 133, label = 'Verde Exército Oliva'},
        },        
        Chameleon = {
            {id = 161, label = 'Pérola Vermelha Anodizada'},
            {id = 162, label = 'Pérola Vinho Anodizada'},
            {id = 163, label = 'Pérola Roxa Anodizada'},
            {id = 164, label = 'Pérola Azul Anodizada'},
            {id = 165, label = 'Pérola Verde Anodizada'},
            {id = 166, label = 'Pérola Limão Anodizada'},
            {id = 167, label = 'Pérola Cobre Anodizada'},
            {id = 168, label = 'Pérola Bronze Anodizada'},
            {id = 169, label = 'Pérola Champanhe Anodizada'},
            {id = 170, label = 'Pérola Ouro Anodizada'},
            {id = 171, label = 'Transição Verde/Azul'},
            {id = 172, label = 'Transição Verde/Vermelho'},
            {id = 173, label = 'Transição Verde/Marrom'},
            {id = 174, label = 'Transição Verde/Turquesa'},
            {id = 175, label = 'Transição Verde/Roxo'},
            {id = 176, label = 'Transição Azul-Verde-Água'},
            {id = 177, label = 'Transição Turquesa/Vermelho'},
            {id = 178, label = 'Transição Turquesa/Roxo'},
            {id = 179, label = 'Transição Ciano/Roxo'},
            {id = 180, label = 'Transição Azul/Rosa'},
            {id = 181, label = 'Transição Azul/Verde'},
            {id = 182, label = 'Transição Roxo/Vermelho'},
            {id = 183, label = 'Transição Roxo/Verde'},
            {id = 184, label = 'Transição Magenta/Verde'},
            {id = 185, label = 'Transição Magenta/Amarelo'},
            {id = 186, label = 'Transição Borgonha/Verde'},
            {id = 187, label = 'Transição Magenta/Ciano'},
            {id = 188, label = 'Transição Cobre/Roxo'},
            {id = 189, label = 'Transição Magenta/Laranja'},
            {id = 190, label = 'Transição Vermelho/Laranja'},
            {id = 191, label = 'Transição Laranja/Roxo'},
            {id = 192, label = 'Transição Laranja/Azul'},
            {id = 193, label = 'Transição Branco/Roxo'},
            {id = 194, label = 'Transição Vermelho/Arco-íris'},
            {id = 195, label = 'Transição Azul/Arco-íris'},
            {id = 196, label = 'Pérola Verde Escuro'},
            {id = 197, label = 'Pérola Verde-Água Escuro'},
            {id = 198, label = 'Pérola Azul Escuro'},
            {id = 199, label = 'Pérola Roxo Escuro'},
            {id = 200, label = 'Pérola Óleo Derramado'},
            {id = 201, label = 'Pérola Verde Claro'},
            {id = 202, label = 'Pérola Azul Claro'},
            {id = 203, label = 'Pérola Roxa Claro'},
            {id = 204, label = 'Pérola Rosa Claro'},
            {id = 205, label = 'Pérola Branca Off'},
            {id = 206, label = 'Pérola Rosa Fofa'},
            {id = 207, label = 'Pérola Amarela Bebê'},
            {id = 208, label = 'Pérola Verde Bebê'},
            {id = 209, label = 'Pérola Azul Bebê'},
            {id = 210, label = 'Pérola Creme'},
            {id = 211, label = 'Pérola Prismática Branca'},
            {id = 212, label = 'Pérola Prismática Grafite'},
            {id = 213, label = 'Pérola Prismática Azul'},
            {id = 214, label = 'Pérola Prismática Roxa'},
            {id = 215, label = 'Pérola Prismática Rosa Choque'},
            {id = 216, label = 'Pérola Prismática Vermelha'},
            {id = 217, label = 'Pérola Prismática Verde'},
            {id = 218, label = 'Pérola Prismática Preta'},
            {id = 219, label = 'Pérola Prismática Derramamento de Óleo'},
            {id = 220, label = 'Pérola Prismática Arco-íris'},
            {id = 221, label = 'Pérola Holográfica Preta'},
            {id = 222, label = 'Pérola Holográfica Branca'},
            {id = 223, label = 'Especiais Fubuki-jo: Monocromático'},
            {id = 224, label = 'Especiais Fubuki-jo: Noite e Dia'},
            {id = 225, label = 'Especiais Fubuki-jo: O Perdedor'},
            {id = 226, label = 'Especiais Fubuki-jo: Sprunk Extremo'},
            {id = 227, label = 'Especiais Fubuki-jo: Vice City'},
            {id = 228, label = 'Especiais Fubuki-jo: Noite Synthwave'},
            {id = 229, label = 'Especiais Fubuki-jo: Quatro Estações'},
            {id = 230, label = 'Especiais Fubuki-jo: Retrocesso M9'},
            {id = 231, label = 'Especiais Fubuki-jo: Chiclete'},
            {id = 232, label = 'Especiais Fubuki-jo: Arco-íris Completo'},
            {id = 233, label = 'Especiais Fubuki-jo: Pôr do Sol'},
            {id = 234, label = 'Especiais Fubuki-jo: Os Sete'},
            {id = 235, label = 'Especiais Fubuki-jo: Kamen Rider'},
            {id = 236, label = 'Especiais Fubuki-jo: Cromático'},
            {id = 237, label = 'Especiais Fubuki-jo: É Natal!'},
            {id = 238, label = 'Especiais Fubuki-jo: Temperatura'},
            {id = 239, label = 'Especiais Fubuki-jo: Distintivo HSW'},
            {id = 240, label = 'Especiais Fubuki-jo: Raios Anodizados'},
            {id = 241, label = 'Especiais Fubuki-jo: Esmeraldas'},
            {id = 242, label = 'Especiais Fubuki-jo: Castelo Fubuki'},
        }
    } ,   
    modLabels = {
        [11] = { -- Motor
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Motor 1'},
            {id = 1,  label = 'Motor 2'},
            {id = 2,  label = 'Motor 3'},
            {id = 3,  label = 'Motor 4'},
        },
        [12] = { -- Freio
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Freios 1'},
            {id = 1,  label = 'Freios 2'},
            {id = 2,  label = 'Freios 3'},
        },
        [13] = { -- Transmissão
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Transmissão 1'},
            {id = 1,  label = 'Transmissão 2'},
            {id = 2,  label = 'Transmissão 3'},
            {id = 3,  label = 'Transmissão 4'},
        },
        [14] = { -- Buzina
            {id = 0,  label = 'Buzina de Caminhão'},
            {id = 1,  label = 'Buzina de Polícia'},
            {id = 2,  label = 'Buzina de Palhaço'},
            {id = 3,  label = 'Buzina Musical 1'},
            {id = 4,  label = 'Buzina Musical 2'},
            {id = 5,  label = 'Buzina Musical 3'},
            {id = 6,  label = 'Buzina Musical 4'},
            {id = 7,  label = 'Buzina Musical 5'},
            {id = 8,  label = 'Trombone Triste'},
            {id = 9,  label = 'Buzina Clássica 1'},
            {id = 10, label = 'Buzina Clássica 2'},
            {id = 11, label = 'Buzina Clássica 3'},
            {id = 12, label = 'Buzina Clássica 4'},
            {id = 13, label = 'Buzina Clássica 5'},
            {id = 14, label = 'Buzina Clássica 6'},
            {id = 15, label = 'Buzina Clássica 7'},
            {id = 16, label = 'Escala - Dó'},
            {id = 17, label = 'Escala - Ré'},
            {id = 18, label = 'Escala - Mi'},
            {id = 19, label = 'Escala - Fá'},
            {id = 20, label = 'Escala - Sol'},
            {id = 21, label = 'Escala - Lá'},
            {id = 22, label = 'Escala - Si'},
            {id = 23, label = 'Escala - Dó'},
            {id = 24, label = 'Buzina de Jazz 1'},
            {id = 25, label = 'Buzina de Jazz 2'},
            {id = 26, label = 'Buzina de Jazz 3'},
            {id = 27, label = 'Loop de Buzina de Jazz'},
            {id = 28, label = 'Hino Nacional 1'},
            {id = 29, label = 'Hino Nacional 2'},
            {id = 30, label = 'Hino Nacional 3'},
            {id = 31, label = 'Hino Nacional 4'},
            {id = 32, label = 'Loop Buzina Clássica 8'},
            {id = 33, label = 'Loop Buzina Clássica 9'},
            {id = 34, label = 'Loop Buzina Clássica 10'},
            {id = 35, label = 'Buzina Clássica 8'},
            {id = 36, label = 'Buzina Clássica 9'},
            {id = 37, label = 'Buzina Clássica 10'},
            {id = 38, label = 'Loop Fúnebre'},
            {id = 39, label = 'Fúnebre'},
            {id = 40, label = 'Loop Assustador'},
            {id = 41, label = 'Assustador'},
            {id = 42, label = 'Loop San Andreas'},
            {id = 43, label = 'San Andreas'},
            {id = 44, label = 'Loop Liberty City'},
            {id = 45, label = 'Liberty City'},
            {id = 46, label = 'Loop Festivo 1'},
            {id = 47, label = 'Festivo 1'},
            {id = 48, label = 'Loop Festivo 2'},
            {id = 49, label = 'Festivo 2'},
            {id = 50, label = 'Loop Festivo 3'},
            {id = 51, label = 'Festivo 3'},
            {id = 52, label = 'Loop Buzina de Ar Baixo'},
            {id = 53, label = 'Buzina de Ar Baixo'},
            {id = 54, label = 'Loop Buzina de Ar Médio'},
            {id = 55, label = 'Buzina de Ar Médio'},
            {id = 56, label = 'Loop Buzina de Ar Alto'},
            {id = 57, label = 'Buzina de Ar Alto'},
        },
        [15] = { -- Suspensão
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Suspensão 1'},
            {id = 1,  label = 'Suspensão 2'},
            {id = 2,  label = 'Suspensão 3'},
            {id = 3,  label = 'Suspensão 4'},
            {id = 4,  label = 'Suspensão 5'},
        },
        [16] = { -- Blindagem
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Blindagem 1'},
            {id = 1,  label = 'Blindagem 2'},
            {id = 2,  label = 'Blindagem 3'},
            {id = 3,  label = 'Blindagem 4'},
            {id = 4,  label = 'Blindagem 5'},
        },
    },
    
    xenon = {
        {id = -1, label = 'Padrão'},
        {id = 0,  label = 'Branco'},
        {id = 1,  label = 'Azul'},
        {id = 2,  label = 'Azul Elétrico'},
        {id = 3,  label = 'Verde Menta'},
        {id = 4,  label = 'Verde Limão'},
        {id = 5,  label = 'Amarelo'},
        {id = 6,  label = 'Chuva Dourada'},
        {id = 7,  label = 'Laranja'},
        {id = 8,  label = 'Vermelho'},
        {id = 9,  label = 'Rosa de Pônei'},
        {id = 10, label = 'Rosa Quente'},
        {id = 11, label = 'Roxo'},
        {id = 12, label = 'Luz Negra'},
    },
    windowTints = {
        {id = 0, label = 'Nenhuma'},
        {id = 1, label = 'Preto Puro'},
        {id = 2, label = 'Fumo Escuro'},
        {id = 3, label = 'Fumo Claro'},
        {id = 4, label = 'Padrão'},
        {id = 5, label = 'Verde'},
    },
    plateIndexes = {
        {id = 0, label = 'Azul em Branco 1'},
        {id = 1, label = 'Amarelo em Preto'},
        {id = 2, label = 'Amarelo em Azul'},
        {id = 3, label = 'Azul em Branco 2'},
        {id = 4, label = 'Azul em Branco 3'},
        {id = 5, label = 'Yankton'},
        {id = 6, label = 'Ecola'},
        {id = 7, label = 'Las Venturas'},
        {id = 8, label = 'Liberty City'},
        {id = 9, label = 'Encontro de Carros de Los Santos'},
        {id = 10, label = 'Pânico de Los Santos'},
        {id = 11, label = 'All-Stars Pounders'},
        {id = 12, label = 'Sprunk'}
    },
    neon = {
        {id = 0, label = 'Esquerda'},
        {id = 1, label = 'Direita'},
        {id = 2, label = 'Frente'},
        {id = 3, label = 'Traseira'},
    },
    neonColors = {
        {label = 'Branco',         r = 222, g = 222, b = 255},
        {label = 'Azul',          r = 2,   g = 21,  b = 255},
        {label = 'Azul Elétrico', r = 3,   g = 83,  b = 255},
        {label = 'Verde Menta',    r = 0,   g = 255, b = 140},
        {label = 'Verde Limão',    r = 94,  g = 255, b = 1},
        {label = 'Amarelo',        r = 255, g = 255, b = 0},
        {label = 'Chuva Dourada', r = 255, g = 150, b = 0},
        {label = 'Laranja',        r = 255, g = 62,  b = 0},
        {label = 'Vermelho',           r = 255, g = 1,   b = 1},
        {label = 'Rosa de Pônei',     r = 255, g = 50,  b = 100},
        {label = 'Rosa Quente',      r = 255, g = 5,   b = 190},
        {label = 'Roxo',        r = 35,  g = 1,   b = 255},
        {label = 'Luz Negra',    r = 15,  g = 3,   b = 255},
    },
    tyreSmoke = {
        {label = 'Fumaça Branca',  r = 254, g = 254, b = 254},
        {label = 'Fumaça Preta',  r = 1,   g = 1,   b = 1},
        {label = 'Fumaça Azul',   r = 0,   g = 150, b = 255},
        {label = 'Fumaça Amarela', r = 255, g = 255, b = 50},
        {label = 'Fumaça Laranja', r = 255, g = 153, b = 51},
        {label = 'Fumaça Vermelha',    r = 255, g = 10,  b = 10},
        {label = 'Fumaça Verde',  r = 10,  g = 255, b = 10},
        {label = 'Fumaça Roxa', r = 153, g = 10,  b = 153},
        {label = 'Fumaça Rosa',   r = 255, g = 102, b = 178},
        {label = 'Fumaça Cinza',   r = 128, g = 128, b = 128},
    },
    wheels = {
        {id = 0, label = 'Esportivas'},
        {id = 1, label = 'Muscle'},
        {id = 2, label = 'Lowrider'},
        {id = 3, label = 'SUV'},
        {id = 4, label = 'Off-road'},
        {id = 5, label = 'Tuner'},
        {id = 6, label = 'Roda Dianteira de Bicicleta'},
        {id = 7, label = 'Hi-end'},
        {id = 8, label = 'Original do Benny'},
        {id = 9, label = 'Personalizado do Benny'},
        {id = 10, label = 'Aberto'},
        {id = 11, label = 'Rua'},
        {id = 12, label = 'Pista'},
    }
}    