return {
    currency = 'R$',
    mods = {
        {id = 0,  label = 'Spoiler', category = 'body', group = 'Aero', icon = '⬈'},
        {id = 1,  label = 'Para-choque dianteiro', category = 'body', group = 'Body Parts', icon = '▰'},
        {id = 2,  label = 'Para-choque traseiro', category = 'body', group = 'Body Parts', icon = '▰'},
        {id = 3,  label = 'Saia lateral', category = 'body', group = 'Body Parts', icon = '▱'},
        {id = 4,  label = 'Escape', category = 'body', group = 'Body Parts', icon = '≈'},
        {id = 5,  label = 'Gaiola de proteção', category = 'body', group = 'Interior', icon = '⛶'},
        {id = 6,  label = 'Grade', category = 'body', group = 'Body Parts', icon = '▥'},
        {id = 7,  label = 'Capô', category = 'body', group = 'Body Parts', icon = '⌂'},
        {id = 8,  label = 'Para-lama esquerdo', category = 'body', group = 'Body Parts', icon = '◧'},
        {id = 9,  label = 'Para-lama direito', category = 'body', group = 'Body Parts', icon = '◨'},
        {id = 10, label = 'Teto', category = 'body', group = 'Body Parts', icon = '⬒'},
        {id = 11, label = 'Melhoria do motor', category = 'performance', group = 'Performance', icon = '⚙'},
        {id = 12, label = 'Melhoria dos freios', category = 'performance', group = 'Performance', icon = '⛔'},
        {id = 13, label = 'Melhoria da transmissão', category = 'performance', group = 'Performance', icon = '⇅'},
        {id = 14, label = 'Buzinas', category = 'body', group = 'Utilidades', icon = '♪'},
        {id = 15, label = 'Melhoria da suspensão', category = 'performance', group = 'Performance', icon = '⇵'},
        {id = 16, label = 'Melhoria da blindagem', category = 'performance', group = 'Performance', icon = '⛨'},
        {id = 17, label = 'Nitro', category = 'performance', group = 'Performance', enabled = false, icon = '✦'},
        {id = 18, label = 'Melhoria do turbo', category = 'performance', group = 'Performance', icon = '➤'},
        {id = 19, label = 'Subwoofer', category = 'body', group = 'Interior', icon = '◉'},
        {id = 21, label = 'Hidráulica', category = 'body', group = 'Utilidades', icon = '⇳'},
        {id = 25, label = 'Suporte de placa', category = 'body', group = 'Placas', icon = '▣'},
        {id = 26, label = 'Saia frontal', category = 'body', group = 'Body Parts', icon = '▰'},
        {id = 27, label = 'Guarnição A', category = 'body', group = 'Body Parts', icon = '◇'},
        {id = 28, label = 'Ornamentos', category = 'body', group = 'Body Parts', icon = '✧'},
        {id = 29, label = 'Painel', category = 'body', group = 'Interior', icon = '▤'},
        {id = 30, label = 'Mostrador', category = 'body', group = 'Interior', icon = '◌'},
        {id = 31, label = 'Alto-falante de porta', category = 'body', group = 'Interior', icon = '◍'},
        {id = 32, label = 'Assentos', category = 'body', group = 'Interior', icon = '▦'},
        {id = 33, label = 'Volante', category = 'body', group = 'Interior', icon = '◎'},
        {id = 34, label = 'Alavanca de câmbio', category = 'body', group = 'Interior', icon = '↕'},
        {id = 35, label = 'Placa', category = 'plates', group = 'Placas', icon = '▣'},
        {id = 36, label = 'Alto-falante', category = 'body', group = 'Interior', icon = '◍'},
        {id = 37, label = 'Porta-malas', category = 'body', group = 'Body Parts', icon = '▭'},
        {id = 38, label = 'Hidráulico', category = 'body', group = 'Utilidades', icon = '⇳'},
        {id = 39, label = 'Bloco do motor', category = 'body', group = 'Motor', icon = '▧'},
        {id = 40, label = 'Filtro de ar', category = 'body', group = 'Motor', icon = '◫'},
        {id = 41, label = 'Estrutural', category = 'body', group = 'Body Parts', icon = '▥'},
        {id = 42, label = 'Capa do arco', category = 'body', group = 'Body Parts', icon = '◬'},
        {id = 43, label = 'Antena', category = 'body', group = 'Body Parts', icon = '⌁'},
        {id = 44, label = 'Guarnição B', category = 'body', group = 'Body Parts', icon = '◇'},
        {id = 45, label = 'Tanque de combustível', category = 'body', group = 'Body Parts', icon = '⬚'},
        {id = 46, label = 'Entrada de ar lateral', category = 'body', group = 'Body Parts', icon = '◫'},
        {id = 47, label = 'Faróis', category = 'lights', group = 'Iluminação', icon = '✦'},
        {id = 48, label = 'Livery', category = 'lights', group = 'Visual', icon = '▨'},
        {id = 49, label = 'Barra de luz', category = 'lights', group = 'Iluminação', icon = '✧'},
    },
    modLabels = {
        [11] = {
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Motor 1'},
            {id = 1,  label = 'Motor 2'},
            {id = 2,  label = 'Motor 3'},
            {id = 3,  label = 'Motor 4'},
        },
        [12] = {
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Freios 1'},
            {id = 1,  label = 'Freios 2'},
            {id = 2,  label = 'Freios 3'},
        },
        [13] = {
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Transmissão 1'},
            {id = 1,  label = 'Transmissão 2'},
            {id = 2,  label = 'Transmissão 3'},
            {id = 3,  label = 'Transmissão 4'},
        },
        [14] = {
            {id = 0,  label = 'Buzina de Caminhão'},
            {id = 1,  label = 'Buzina de Polícia'},
            {id = 2,  label = 'Buzina de Palhaço'},
            {id = 3,  label = 'Buzina Musical 1'},
            {id = 4,  label = 'Buzina Musical 2'},
            {id = 5,  label = 'Buzina Musical 3'},
            {id = 6,  label = 'Buzina Musical 4'},
            {id = 7,  label = 'Buzina Musical 5'},
            {id = 8,  label = 'Trombone Triste'},
            {id = 9,  label = 'Buzina Clássica 1'},
            {id = 10, label = 'Buzina Clássica 2'},
            {id = 11, label = 'Buzina Clássica 3'},
            {id = 12, label = 'Buzina Clássica 4'},
            {id = 13, label = 'Buzina Clássica 5'},
            {id = 14, label = 'Buzina Clássica 6'},
            {id = 15, label = 'Buzina Clássica 7'},
            {id = 16, label = 'Escala - Dó'},
            {id = 17, label = 'Escala - Ré'},
            {id = 18, label = 'Escala - Mi'},
            {id = 19, label = 'Escala - Fá'},
            {id = 20, label = 'Escala - Sol'},
            {id = 21, label = 'Escala - Lá'},
            {id = 22, label = 'Escala - Si'},
            {id = 23, label = 'Escala - Dó'},
            {id = 24, label = 'Buzina de Jazz 1'},
            {id = 25, label = 'Buzina de Jazz 2'},
            {id = 26, label = 'Buzina de Jazz 3'},
            {id = 27, label = 'Loop de Buzina de Jazz'},
            {id = 28, label = 'Hino Nacional 1'},
            {id = 29, label = 'Hino Nacional 2'},
            {id = 30, label = 'Hino Nacional 3'},
            {id = 31, label = 'Hino Nacional 4'},
            {id = 32, label = 'Loop Buzina Clássica 8'},
            {id = 33, label = 'Loop Buzina Clássica 9'},
            {id = 34, label = 'Loop Buzina Clássica 10'},
            {id = 35, label = 'Buzina Clássica 8'},
            {id = 36, label = 'Buzina Clássica 9'},
            {id = 37, label = 'Buzina Clássica 10'},
            {id = 38, label = 'Loop Fúnebre'},
            {id = 39, label = 'Fúnebre'},
            {id = 40, label = 'Loop Assustador'},
            {id = 41, label = 'Assustador'},
            {id = 42, label = 'Loop San Andreas'},
            {id = 43, label = 'San Andreas'},
            {id = 44, label = 'Loop Liberty City'},
            {id = 45, label = 'Liberty City'},
            {id = 46, label = 'Loop Festivo 1'},
            {id = 47, label = 'Festivo 1'},
            {id = 48, label = 'Loop Festivo 2'},
            {id = 49, label = 'Festivo 2'},
            {id = 50, label = 'Loop Festivo 3'},
            {id = 51, label = 'Festivo 3'},
            {id = 52, label = 'Loop Buzina de Ar Baixo'},
            {id = 53, label = 'Buzina de Ar Baixo'},
            {id = 54, label = 'Loop Buzina de Ar Médio'},
            {id = 55, label = 'Buzina de Ar Médio'},
            {id = 56, label = 'Loop Buzina de Ar Alto'},
            {id = 57, label = 'Buzina de Ar Alto'},
        },
        [15] = {
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Suspensão 1'},
            {id = 1,  label = 'Suspensão 2'},
            {id = 2,  label = 'Suspensão 3'},
            {id = 3,  label = 'Suspensão 4'},
            {id = 4,  label = 'Suspensão 5'},
        },
        [16] = {
            {id = -1, label = 'Padrão'},
            {id = 0,  label = 'Blindagem 1'},
            {id = 1,  label = 'Blindagem 2'},
            {id = 2,  label = 'Blindagem 3'},
            {id = 3,  label = 'Blindagem 4'},
            {id = 4,  label = 'Blindagem 5'},
        },
    },
    xenon = {
        {id = -1, label = 'Padrão'},
        {id = 0,  label = 'Branco'},
        {id = 1,  label = 'Azul'},
        {id = 2,  label = 'Azul Elétrico'},
        {id = 3,  label = 'Verde Menta'},
        {id = 4,  label = 'Verde Limão'},
        {id = 5,  label = 'Amarelo'},
        {id = 6,  label = 'Chuva Dourada'},
        {id = 7,  label = 'Laranja'},
        {id = 8,  label = 'Vermelho'},
        {id = 9,  label = 'Rosa de Pônei'},
        {id = 10, label = 'Rosa Quente'},
        {id = 11, label = 'Roxo'},
        {id = 12, label = 'Luz Negra'},
    },
    windowTints = {
        {id = 0, label = 'Nenhuma'},
        {id = 1, label = 'Preto Puro'},
        {id = 2, label = 'Fumo Escuro'},
        {id = 3, label = 'Fumo Claro'},
        {id = 4, label = 'Padrão'},
        {id = 5, label = 'Verde'},
    },
    plateIndexes = {
        {id = 0, label = 'Azul em Branco 1'},
        {id = 1, label = 'Amarelo em Preto'},
        {id = 2, label = 'Amarelo em Azul'},
        {id = 3, label = 'Azul em Branco 2'},
        {id = 4, label = 'Azul em Branco 3'},
        {id = 5, label = 'Yankton'},
        {id = 6, label = 'Ecola'},
        {id = 7, label = 'Las Venturas'},
        {id = 8, label = 'Liberty City'},
        {id = 9, label = 'Encontro de Carros de Los Santos'},
        {id = 10, label = 'Pânico de Los Santos'},
        {id = 11, label = 'All-Stars Pounders'},
        {id = 12, label = 'Sprunk'}
    },
    neon = {
        {id = 0, label = 'Esquerda'},
        {id = 1, label = 'Direita'},
        {id = 2, label = 'Frente'},
        {id = 3, label = 'Traseira'},
    },
    neonColors = {
        {label = 'Branco', r = 222, g = 222, b = 255},
        {label = 'Azul', r = 2, g = 21, b = 255},
        {label = 'Azul Elétrico', r = 3, g = 83, b = 255},
        {label = 'Verde Menta', r = 0, g = 255, b = 140},
        {label = 'Verde Limão', r = 94, g = 255, b = 1},
        {label = 'Amarelo', r = 255, g = 255, b = 0},
        {label = 'Chuva Dourada', r = 255, g = 150, b = 0},
        {label = 'Laranja', r = 255, g = 62, b = 0},
        {label = 'Vermelho', r = 255, g = 1, b = 1},
        {label = 'Rosa de Pônei', r = 255, g = 50, b = 100},
        {label = 'Rosa Quente', r = 255, g = 5, b = 190},
        {label = 'Roxo', r = 35, g = 1, b = 255},
        {label = 'Luz Negra', r = 15, g = 3, b = 255},
    },
    wheels = {
        {id = 0, label = 'Esportivas'},
        {id = 1, label = 'Muscle'},
        {id = 2, label = 'Lowrider'},
        {id = 3, label = 'SUV'},
        {id = 4, label = 'Off-road'},
        {id = 5, label = 'Tuner'},
        {id = 6, label = 'Roda Dianteira de Bicicleta'},
        {id = 7, label = 'Hi-end'},
        {id = 8, label = 'Original do Benny'},
        {id = 9, label = 'Personalizado do Benny'},
        {id = 10, label = 'Aberto'},
        {id = 11, label = 'Rua'},
        {id = 12, label = 'Pista'},
    },
    categories = {
        {id = 'service', label = 'Serviços', icon = '✚', description = 'Reparo rápido e restauração segura do veículo.'},
        {id = 'performance', label = 'Performance', icon = '⚙', description = 'Motor, freios, transmissão, suspensão, turbo e blindagem.'},
        {id = 'body', label = 'Body Parts', icon = '◫', description = 'Spoiler, para-choques, saias, escapamento, capô e interior.'},
        {id = 'wheels', label = 'Rodas', icon = '◎', description = 'Troca de rodas e seleção por classe compatível.'},
        {id = 'lights', label = 'Luzes & Vidros', icon = '✦', description = 'Xenon, neon, fumê e livery quando disponível.'},
        {id = 'plates', label = 'Placas', icon = '▣', description = 'Estilo da placa e suportes compatíveis.'},
        {id = 'extras', label = 'Extras', icon = '⋯', description = 'Ative ou desative extras nativos do veículo.'},
    }
}
