return {
    currency = 'R$',
    controls = {
        openMenu = 38,
    },
    camera = {
        radius = 5.2,
        minRadius = 2.5,
        maxRadius = 9.5,
        scrollStep = 0.4,
        pitchMin = -12.0,
        pitchMax = 35.0,
        focusOffset = vec3(0.0, 0.0, 0.6),
    },
    categories = {
        { id = 'service', label = 'Serviços', icon = 'hammer', description = 'Reparo e recuperação do veículo.' },
        { id = 'performance', label = 'Performance', icon = 'gauge-high', description = 'Motor, freios, transmissão, suspensão, turbo e blindagem.' },
        { id = 'body', label = 'Carroceria', icon = 'car-side', description = 'Spoilers, parachoques, capô, interior e demais peças.' },
        { id = 'wheels', label = 'Rodas', icon = 'compact-disc', description = 'Tipos de roda, rodas dianteiras e traseiras de moto.' },
        { id = 'lights', label = 'Luzes & Vidros', icon = 'lightbulb', description = 'Xenon, neon, película e livery compatíveis.' },
        { id = 'plates', label = 'Placas', icon = 'id-card', description = 'Suportes e estilos de placa.' },
        { id = 'extras', label = 'Extras', icon = 'ellipsis', description = 'Ativação e desativação de extras nativos.' },
    },
    mods = {
        { id = 0,  label = 'Spoiler', category = 'body', group = 'Aero', icon = 'wind' },
        { id = 1,  label = 'Parachoque dianteiro', category = 'body', group = 'Carroceria', icon = 'car-side' },
        { id = 2,  label = 'Parachoque traseiro', category = 'body', group = 'Carroceria', icon = 'car-side' },
        { id = 3,  label = 'Saia lateral', category = 'body', group = 'Carroceria', icon = 'grip-lines' },
        { id = 4,  label = 'Escape', category = 'body', group = 'Carroceria', icon = 'smog' },
        { id = 5,  label = 'Gaiola de proteção', category = 'body', group = 'Interior', icon = 'border-all' },
        { id = 6,  label = 'Grade', category = 'body', group = 'Carroceria', icon = 'grip-lines-vertical' },
        { id = 7,  label = 'Capô', category = 'body', group = 'Carroceria', icon = 'caret-up' },
        { id = 8,  label = 'Paralama esquerdo', category = 'body', group = 'Carroceria', icon = 'arrows-left-right' },
        { id = 9,  label = 'Paralama direito', category = 'body', group = 'Carroceria', icon = 'arrows-left-right' },
        { id = 10, label = 'Teto', category = 'body', group = 'Carroceria', icon = 'grip-lines' },
        { id = 11, label = 'Motor', category = 'performance', group = 'Performance', icon = 'gear' },
        { id = 12, label = 'Freios', category = 'performance', group = 'Performance', icon = 'ban' },
        { id = 13, label = 'Transmissão', category = 'performance', group = 'Performance', icon = 'right-left' },
        { id = 14, label = 'Buzina', category = 'body', group = 'Utilidades', icon = 'music' },
        { id = 15, label = 'Suspensão', category = 'performance', group = 'Performance', icon = 'arrows-up-down' },
        { id = 16, label = 'Blindagem', category = 'performance', group = 'Performance', icon = 'shield-halved' },
        { id = 18, label = 'Turbo', category = 'performance', group = 'Performance', icon = 'gauge' },
        { id = 19, label = 'Subwoofer', category = 'body', group = 'Interior', icon = 'volume-high' },
        { id = 21, label = 'Hidráulica', category = 'body', group = 'Utilidades', icon = 'arrows-up-down' },
        { id = 25, label = 'Suporte de placa', category = 'plates', group = 'Placas', icon = 'id-card' },
        { id = 26, label = 'Saia frontal', category = 'body', group = 'Carroceria', icon = 'grip-lines' },
        { id = 27, label = 'Guarnição A', category = 'body', group = 'Carroceria', icon = 'diamond' },
        { id = 28, label = 'Ornamentos', category = 'body', group = 'Carroceria', icon = 'wand-magic-sparkles' },
        { id = 29, label = 'Painel', category = 'body', group = 'Interior', icon = 'table-cells-large' },
        { id = 30, label = 'Mostrador', category = 'body', group = 'Interior', icon = 'circle-dot' },
        { id = 31, label = 'Alto-falante de porta', category = 'body', group = 'Interior', icon = 'volume-high' },
        { id = 32, label = 'Assentos', category = 'body', group = 'Interior', icon = 'couch' },
        { id = 33, label = 'Volante', category = 'body', group = 'Interior', icon = 'circle-notch' },
        { id = 34, label = 'Alavanca de câmbio', category = 'body', group = 'Interior', icon = 'up-down' },
        { id = 35, label = 'Placa', category = 'plates', group = 'Placas', icon = 'id-card' },
        { id = 36, label = 'Alto-falante', category = 'body', group = 'Interior', icon = 'volume-high' },
        { id = 37, label = 'Porta-malas', category = 'body', group = 'Carroceria', icon = 'box-open' },
        { id = 38, label = 'Hidráulico', category = 'body', group = 'Utilidades', icon = 'arrows-up-down' },
        { id = 39, label = 'Bloco do motor', category = 'body', group = 'Motor', icon = 'gear' },
        { id = 40, label = 'Filtro de ar', category = 'body', group = 'Motor', icon = 'wind' },
        { id = 41, label = 'Estrutural', category = 'body', group = 'Carroceria', icon = 'grip-lines-vertical' },
        { id = 42, label = 'Capa do arco', category = 'body', group = 'Carroceria', icon = 'circle-half-stroke' },
        { id = 43, label = 'Antena', category = 'body', group = 'Carroceria', icon = 'tower-broadcast' },
        { id = 44, label = 'Guarnição B', category = 'body', group = 'Carroceria', icon = 'diamond' },
        { id = 45, label = 'Tanque de combustível', category = 'body', group = 'Carroceria', icon = 'gas-pump' },
        { id = 46, label = 'Entrada de ar lateral', category = 'body', group = 'Carroceria', icon = 'fan' },
        { id = 47, label = 'Faróis', category = 'lights', group = 'Iluminação', icon = 'lightbulb' },
        { id = 48, label = 'Livery', category = 'lights', group = 'Visual', icon = 'paint-roller' },
        { id = 49, label = 'Barra de luz', category = 'lights', group = 'Iluminação', icon = 'lightbulb' },
    },
    wheels = {
        { id = 0, label = 'Esportivas' },
        { id = 1, label = 'Muscle' },
        { id = 2, label = 'Lowrider' },
        { id = 3, label = 'SUV' },
        { id = 4, label = 'Off-road' },
        { id = 5, label = 'Tuner' },
        { id = 6, label = 'Bike dianteira' },
        { id = 7, label = 'High-end' },
        { id = 8, label = 'Benny original' },
        { id = 9, label = 'Benny custom' },
        { id = 10, label = 'Open wheel' },
        { id = 11, label = 'Rua' },
        { id = 12, label = 'Pista' },
    },
    plateIndexes = {
        { id = 0, label = 'Azul em branco 1' },
        { id = 1, label = 'Amarelo em preto' },
        { id = 2, label = 'Amarelo em azul' },
        { id = 3, label = 'Azul em branco 2' },
        { id = 4, label = 'Azul em branco 3' },
        { id = 5, label = 'Yankton' },
        { id = 6, label = 'Ecola' },
        { id = 7, label = 'Las Venturas' },
        { id = 8, label = 'Liberty City' },
        { id = 9, label = 'LS Car Meet' },
        { id = 10, label = 'LS Panic' },
        { id = 11, label = 'All-Stars' },
        { id = 12, label = 'Sprunk' },
    },
    windowTints = {
        { id = 0, label = 'Nenhuma' },
        { id = 1, label = 'Preto puro' },
        { id = 2, label = 'Fumê escuro' },
        { id = 3, label = 'Fumê claro' },
        { id = 4, label = 'Padrão' },
        { id = 5, label = 'Verde' },
    },
    xenon = {
        { id = -1, label = 'Padrão' },
        { id = 0, label = 'Branco' },
        { id = 1, label = 'Azul' },
        { id = 2, label = 'Azul elétrico' },
        { id = 3, label = 'Verde menta' },
        { id = 4, label = 'Verde limão' },
        { id = 5, label = 'Amarelo' },
        { id = 6, label = 'Dourado' },
        { id = 7, label = 'Laranja' },
        { id = 8, label = 'Vermelho' },
        { id = 9, label = 'Rosa claro' },
        { id = 10, label = 'Rosa quente' },
        { id = 11, label = 'Roxo' },
        { id = 12, label = 'Luz negra' },
    },
    neon = {
        { id = 0, label = 'Esquerda' },
        { id = 1, label = 'Direita' },
        { id = 2, label = 'Frente' },
        { id = 3, label = 'Traseira' },
    },
    neonColors = {
        { label = 'Branco', r = 222, g = 222, b = 255 },
        { label = 'Azul', r = 2, g = 21, b = 255 },
        { label = 'Azul elétrico', r = 3, g = 83, b = 255 },
        { label = 'Verde menta', r = 0, g = 255, b = 140 },
        { label = 'Verde limão', r = 94, g = 255, b = 1 },
        { label = 'Amarelo', r = 255, g = 255, b = 0 },
        { label = 'Dourado', r = 255, g = 150, b = 0 },
        { label = 'Laranja', r = 255, g = 62, b = 0 },
        { label = 'Vermelho', r = 255, g = 1, b = 1 },
        { label = 'Rosa claro', r = 255, g = 50, b = 100 },
        { label = 'Rosa quente', r = 255, g = 5, b = 190 },
        { label = 'Roxo', r = 35, g = 1, b = 255 },
        { label = 'Luz negra', r = 15, g = 3, b = 255 },
    },
    vehicleClasses = {
        [0] = 'Compacto',
        [1] = 'Sedã',
        [2] = 'SUV',
        [3] = 'Coupé',
        [4] = 'Muscle',
        [5] = 'Esportivo clássico',
        [6] = 'Esportivo',
        [7] = 'Super',
        [8] = 'Moto',
        [9] = 'Off-road',
        [10] = 'Industrial',
        [11] = 'Utilitário',
        [12] = 'Van',
        [13] = 'Bicicleta',
        [14] = 'Barco',
        [15] = 'Helicóptero',
        [16] = 'Avião',
        [17] = 'Serviço',
        [18] = 'Emergência',
        [19] = 'Militar',
        [20] = 'Comercial',
        [21] = 'Trem',
        [22] = 'Open wheel',
    },
    modLabels = {
        [11] = {
            [-1] = 'Original', [0] = 'Motor 1', [1] = 'Motor 2', [2] = 'Motor 3', [3] = 'Motor 4',
        },
        [12] = {
            [-1] = 'Original', [0] = 'Freios 1', [1] = 'Freios 2', [2] = 'Freios 3',
        },
        [13] = {
            [-1] = 'Original', [0] = 'Transmissão 1', [1] = 'Transmissão 2', [2] = 'Transmissão 3', [3] = 'Transmissão 4',
        },
        [15] = {
            [-1] = 'Original', [0] = 'Suspensão 1', [1] = 'Suspensão 2', [2] = 'Suspensão 3', [3] = 'Suspensão 4', [4] = 'Suspensão 5',
        },
        [16] = {
            [-1] = 'Original', [0] = 'Blindagem 1', [1] = 'Blindagem 2', [2] = 'Blindagem 3', [3] = 'Blindagem 4', [4] = 'Blindagem 5',
        },
    },
}
